language: ruby

rvm:
  - 2.1.1

branches:
  only:
    - master

before_script:
  - mysql -e 'create database ggp2_test;'
  - cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

bundler_args: "--without development production"